export const hard: Record<string, string> = {
  a: "@4aàáâäãåāăąαа",
  e: "3£€eèéêëēĕėęěεе",
  i: "iìíîïĩīĭįıιи1",
  o: "0oòóôöõøōŏőοо",
  u: "uùúûüũūŭůűųυу",
  c: "©cçćĉċč",
  n: "nñńņňŉŋ",
  s: "sśŝşš§5$",
  z: "zźżž2",
  y: "yýÿŷ",
  l: "lł|1",
  d: "dďđ&",
  r: "rŕř",
  t: "tţť7",
  g: "gğĝǧ9",
  h: "hĥħ"
};
export const medium: Record<string, string> = {
  a: "a4@",
  e: "e3€",
  i: "i1",
  o: "o0",
  u: "u",
  c: "c©",
  n: "n",
  s: "s5§$",
  z: "z2",
  y: "yÿ",
  l: "l1|",
  d: "d&",
  r: "r",
  t: "t7",
  g: "g9",
  h: "h"
};
export const easy: Record<string, string> = {
  a: "a4",
  e: "e3",
  i: "li1",
  o: "o0",
  u: "u",
  c: "c",
  n: "n",
  s: "s5",
  z: "z2",
  y: "y",
  l: "l1",
  d: "d",
  r: "r",
  t: "t7",
  g: "g9",
  h: "h"
};